services:
  postgres:
    image: postgres:12.22
    container_name: superfoca
    restart: always
    networks:
      - postgres-network
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./_db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge
